let x=5,y=8;
console.log(x+y); //Addition
console.log(x-y); //Subtraction
console.log(x*y);   //Multiplication                
console.log(x/y);   //Division
console.log(x%y);  //Modulus
console.log(x**y); //Exponentiation
console.log(++x);  //Increment
console.log(--y);  //Decrement
